# Generated by Django 5.1.4 on 2024-12-11 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_initial'),
        ('registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='district',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_client', to='productapp.districtmodel', verbose_name='Rayon'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_client', to='productapp.citymodel', verbose_name='Şəhər'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='village',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_client', to='productapp.villagemodel', verbose_name='Kənd'),
        ),
    ]
