# Generated by Django 5.1.4 on 2024-12-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0002_clientmodel_district_alter_clientmodel_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad, soyad')),
            ],
            options={
                'verbose_name': 'Servis edən şəxs',
                'verbose_name_plural': 'Servis edən şəxslər',
            },
        ),
        migrations.CreateModel(
            name='ShuttleServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(blank=True, null=True, verbose_name='Servis xidməti')),
                ('date', models.DateField(verbose_name='Servis tarixi')),
                ('type', models.CharField(choices=[('O', 'Ödənişli'), ('OS', 'Ödənişsiz')], default='OS', max_length=2, verbose_name='Servis tipi')),
                ('price', models.FloatField(default=0, verbose_name='Servis qiyməti')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Qeyd')),
                ('status', models.CharField(choices=[('O', 'Servis olunub'), ('OM', 'Servis olunmayıb')], default='OM', max_length=2, verbose_name='Status')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shuttleservices', to='registrationapp.registrationmodel', verbose_name='Qeydiyyat')),
                ('servicers', models.ManyToManyField(related_name='shuttleservices', to='registrationapp.servicermodel', verbose_name='Servis edən şəxs')),
            ],
            options={
                'verbose_name': 'Servis xidməti',
                'verbose_name_plural': 'Servis xidmətləri',
            },
        ),
    ]
