# Generated by Django 5.1.4 on 2024-12-21 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_initial'),
        ('registrationapp', '0003_servicermodel_shuttleservicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='client_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_client', to='productapp.productmodel', verbose_name='Məhsul'),
        ),
    ]
