# Generated by Django 5.1.4 on 2024-12-24 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_initial'),
        ('registrationapp', '0004_alter_clientmodel_client_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterchangermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi'),
        ),
        migrations.AddField(
            model_name='filterchangermodel',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Maaş'),
        ),
        migrations.AddField(
            model_name='servicermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi'),
        ),
        migrations.AddField(
            model_name='servicermodel',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Maaş'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='client_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_clients', to='productapp.productmodel', verbose_name='Məhsul'),
        ),
    ]
