# Generated by Django 5.1.4 on 2025-01-13 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_initial'),
        ('registrationapp', '0006_changefiltermodel_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_clients', to='productapp.citymodel', verbose_name='Şəhər'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_clients', to='productapp.districtmodel', verbose_name='Rayon'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='village_clients', to='productapp.villagemodel', verbose_name='Kənd'),
        ),
    ]
