# Generated by Django 5.1.4 on 2025-01-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0007_alter_clientmodel_city_alter_clientmodel_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentmodel',
            name='message_status',
            field=models.BooleanField(default=False, verbose_name='Mesaj statusu'),
        ),
    ]
