# Generated by Django 5.1.4 on 2025-01-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0009_remove_sellermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterchangermodel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='servicermodel',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='filterchangermodel',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi 1'),
        ),
        migrations.AddField(
            model_name='filterchangermodel',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi 2'),
        ),
        migrations.AddField(
            model_name='servicermodel',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi 1'),
        ),
        migrations.AddField(
            model_name='servicermodel',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi 2'),
        ),
    ]
