# Generated by Django 5.1.4 on 2025-01-28 00:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationapp', '0010_remove_filterchangermodel_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changefiltermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Filtir dəyişimi', 'verbose_name_plural': 'Filtir dəyişimləri'},
        ),
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Müştəri', 'verbose_name_plural': 'Müştərilər'},
        ),
        migrations.AlterModelOptions(
            name='filterchangermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Filter dəyişdirən', 'verbose_name_plural': 'Filter dəyişdirənlər'},
        ),
        migrations.AlterModelOptions(
            name='installmentinfomodel',
            options={'ordering': ('-id',), 'verbose_name': 'Taksit məlumatı', 'verbose_name_plural': 'Taksit məlumatları'},
        ),
        migrations.AlterModelOptions(
            name='registrationmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Qeydiyyat', 'verbose_name_plural': 'Qeydiyyatlar'},
        ),
        migrations.AlterModelOptions(
            name='sellermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Satıcı', 'verbose_name_plural': 'Satıcılar'},
        ),
        migrations.AlterModelOptions(
            name='servicermodel',
            options={'ordering': ('-id',), 'verbose_name': 'Servis edən şəxs', 'verbose_name_plural': 'Servis edən şəxslər'},
        ),
        migrations.AlterModelOptions(
            name='shuttleservicemodel',
            options={'ordering': ('-id',), 'verbose_name': 'Servis xidməti', 'verbose_name_plural': 'Servis xidmətləri'},
        ),
        migrations.AlterField(
            model_name='changefiltermodel',
            name='category',
            field=models.CharField(choices=[('F', 'Birinci kateqoriya'), ('S', 'İkinci kateqoriya'), ('T', 'Üçüncü kateqoriya'), ('FT', 'Dördüncü kateqoriya')], max_length=2, verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='installmentinfomodel',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ExtraPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateTimeField(verbose_name='Ödəniş tarixi')),
                ('payment_amount', models.FloatField(verbose_name='Ödəniş miqdarı')),
                ('payment_type', models.CharField(choices=[('N', 'Nağd'), ('NS', 'Nağdsız')], default='N', max_length=2, verbose_name='Ödəniş növü')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_payments', to='registrationapp.installmentmodel', verbose_name='Taksit')),
            ],
        ),
    ]
