# Generated by Django 5.1.4 on 2025-01-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermoreinfomodel',
            options={'ordering': ('-id',), 'verbose_name': 'İstifadəçi məlumatları', 'verbose_name_plural': 'İstifadəçilərin məlumatları'},
        ),
    ]
