# Generated by Django 5.1.4 on 2024-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, verbose_name='Şəhər')),
            ],
            options={
                'verbose_name': 'Şəhər',
                'verbose_name_plural': 'Şəhərlər',
            },
        ),
        migrations.CreateModel(
            name='DiscountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.TextField(blank=True, null=True, verbose_name='Endirimin tipi')),
                ('percentage', models.FloatField(blank=True, null=True, verbose_name='Endirim %')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Endirimin miqdarı')),
            ],
            options={
                'verbose_name': 'Endirim',
                'verbose_name_plural': 'Endirimlər',
            },
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=30, verbose_name='Rayon')),
            ],
            options={
                'verbose_name': 'Rayon',
                'verbose_name_plural': 'Rayonlar',
            },
        ),
        migrations.CreateModel(
            name='GiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Hədiyyənin adı')),
            ],
            options={
                'verbose_name': 'Hədiyyə',
                'verbose_name_plural': 'Hədiyyələr',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Məhsulun adı')),
                ('price', models.FloatField(default=0, verbose_name='Məhsulun qiyməti')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='VillageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100, verbose_name='Kənd')),
            ],
            options={
                'verbose_name': 'Kənd',
                'verbose_name_plural': 'Kəndlər',
            },
        ),
    ]
