# Generated by Django 5.1.4 on 2025-01-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citymodel',
            options={'ordering': ('-id',), 'verbose_name': 'Şəhər', 'verbose_name_plural': 'Şəhərlər'},
        ),
        migrations.AlterModelOptions(
            name='discountmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Endirim', 'verbose_name_plural': 'Endirimlər'},
        ),
        migrations.AlterModelOptions(
            name='districtmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Rayon', 'verbose_name_plural': 'Rayonlar'},
        ),
        migrations.AlterModelOptions(
            name='giftmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Hədiyyə', 'verbose_name_plural': 'Hədiyyələr'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Məhsul', 'verbose_name_plural': 'Məhsullar'},
        ),
        migrations.AlterModelOptions(
            name='villagemodel',
            options={'ordering': ('-id',), 'verbose_name': 'Kənd', 'verbose_name_plural': 'Kəndlər'},
        ),
    ]
