# Generated by Django 5.1.4 on 2024-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Ödədiyi ay')),
                ('date', models.DateField(verbose_name='Ödəniş tarixi')),
            ],
            options={
                'verbose_name': 'Günlük ödəniş',
                'verbose_name_plural': 'Günlük ödənişlər',
            },
        ),
    ]
