# Generated by Django 5.1.4 on 2025-01-28 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_intstallment_dailypaymentmodel_installment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailypaymentmodel',
            options={'ordering': ('-id',), 'verbose_name': 'Günlük ödəniş', 'verbose_name_plural': 'Günlük ödənişlər'},
        ),
    ]
