# Generated by Django 5.1.4 on 2025-01-30 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_dailypaymentmodel_options'),
        ('registrationapp', '0011_alter_changefiltermodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDailyPaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Ödənilən ay')),
                ('date', models.DateField(verbose_name='Ödənilən tarix')),
                ('changer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changer_dailypayments', to='registrationapp.filterchangermodel', verbose_name='Filter Dəyişən')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_dailypayments', to='registrationapp.sellermodel', verbose_name='Satıcı')),
                ('servicer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicer_dailypayments', to='registrationapp.servicermodel', verbose_name='Servis xidməti edən')),
            ],
            options={
                'verbose_name': 'Persona üçün günlük ödəniş',
                'verbose_name_plural': 'Persona üçün günlük ödənişlər',
                'ordering': ('-id',),
            },
        ),
    ]
